{% set name = "yaqc" %}
{% set version = "0.2.0" %}
{% set sha256 = "c22f1e73cadf0a5147be6687d05563b412556c7a57bea5711172a010abe65544" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - yaqc

about:
  home: https://yaq.fyi
  dev_url: https://gitlab.com/yaq/yaqc-python
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Generic yaq client, written in Python.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
