{% set name = "yaqc" %}
{% set version = "2020.10.0" %}
{% set sha256 = "bd934e3f8a435c127f648d88fadc4cf19f34e87a3ec8b789057281193056f86c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - fastavro >=0.24.0
    - flit
  run:
    - python >=3.7
    - fastavro >=0.24.0

test:
  imports:
    - yaqc

about:
  home: https://yaq.fyi
  dev_url: https://gitlab.com/yaq/yaq-python
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: Generic yaq client, written in Python.

extra:
  recipe-maintainers:
    - untzag
    - ksunden
